version: '3'
services:
  embulk:
      build: ./embulk
      volumes:
        - ./test:/test
      depends_on:
          - db
  db:
      image: mysql:5.6
      environment:
          MYSQL_ROOT_PASSWORD: bulkload
          MYSQL_USER: bulkload
          MYSQL_PASSWORD: bulkload
          MYSQL_DATABASE: bulkload
